{% set name = "lilio" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lilio-{{ version }}.tar.gz
  sha256: 398e04658aa1df1936054af296afcf50d7b1c8bee18d11333e9fe0545b1526e8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.11
    - hatchling >=1.8.0
    - hatch-vcs
    - pip
  run:
    - python >=3.8,<3.11
    - netcdf4
    - numpy
    - pandas
    - matplotlib-base
    - xarray
    - scikit-learn

test:
  imports:
    - lilio
  commands:
    - pip check
  requires:
    - pip

about:
  summary: python package for generating calendars for machine learning timeseries analysis.
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/AI4S2S/lilio

extra:
  recipe-maintainers:
    - BSchilperoort
